name:                bulmex
version:             4.0.0
github:              "jappeace/bulmex"
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2018 Jappie Klooster"
synopsis:             Reflex infused with bulma (css)
category:             Web

extra-source-files:
- README.md
- ChangeLog.md

description: Bulma is a pure CSS framework. Because of that it can be easily used with reflex.
            This library realizes that combination.
            Bulma already provided styling for a [modal](https://bulma.io/documentation/components/modal/),
            we just [implemented](https://hackage.haskell.org/package/bulmex/docs/Reflex-Bulmex-Modal.html) 
            it for you!
            There are also some helper functions for common tasks.
            such as making server side rendering easier.
            Which is described in a related
            [blogpost](https://jappieklooster.nl/reflex-server-side-html-rendering.html).

ghc-options: -Wall -Wcompat -Wincomplete-uni-patterns -Widentities

dependencies:
- base >= 4.7 && < 5
- reflex >= 0.6.1 && < 0.7
- reflex-dom-core >= 0.5 && < 0.6
- time
- witherable
- containers
- lens # reflex-dom depends on this so can we
- text
- aeson
- jsaddle
- jsaddle-dom
- bytestring
- network-uri
- reflex-dom-helpers >= 0.2.0.1 && < 0.3.0.0 # generate tags fro me
- generic-lens
- keycode

library:
  source-dirs: src

tests:
  unit:
    main:                Spec.hs
    source-dirs:
    - test
    # including extra source dirs allows ghcid to watch
    - src 
    dependencies:
      - hspec
      - hspec-core
